export const FAKE_POPULARS = [
  {
    adult: false,
    backdrop_path: "/jbFkZSsmFFLjqZzxQHTBYyQb0RR.jpg",
    id: 135251,
    name: "The Idol",
    original_language: "en",
    original_name: "The Idol",
    overview:
      "After a nervous breakdown derailed Jocelyn's last tour, she’s determined to claim her rightful status as the greatest and sexiest pop star in America. Her passions are reignited by Tedros, a nightclub impresario with a sordid past. Will her romantic awakening take her to glorious new heights or the deepest and darkest depths of her soul?",
    poster_path: "/gO9k7t9jSdkkWVG0deMZDpELZGw.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 289.285,
    first_air_date: "2023-06-04",
    vote_average: 5.957,
    vote_count: 23,
    origin_country: ["US"],
  },
];

export const FAKE_RECOMMENDS = [
  {
    adult: false,
    backdrop_path: "/uJ16DD1dj4CQLPNCWIoiOF3l8np.jpg",
    id: 100088,
    name: "The Last of Us",
    original_language: "en",
    original_name: "The Last of Us",
    overview:
      "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.",
    poster_path: "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 295.152,
    first_air_date: "2023-01-15",
    vote_average: 8.713,
    vote_count: 3586,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/dNhMPysC8FrveLORB34IO1V7zLo.jpg",
    id: 1104,
    name: "Mad Men",
    original_language: "en",
    original_name: "Mad Men",
    overview:
      "Set in 1960-1970 New York, this sexy, stylized and provocative drama follows the lives of the ruthlessly competitive men and women of Madison Avenue advertising.",
    poster_path: "/seSIJjaUkxvUp0tdcYohncf34Mu.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 51.723,
    first_air_date: "2007-07-19",
    vote_average: 8.102,
    vote_count: 980,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/84XPpjGvxNyExjSuLQe0SzioErt.jpg",
    id: 1396,
    name: "Breaking Bad",
    original_language: "en",
    original_name: "Breaking Bad",
    overview:
      "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
    poster_path: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    media_type: "tv",
    genre_ids: [18, 80],
    popularity: 245.772,
    first_air_date: "2008-01-20",
    vote_average: 8.9,
    vote_count: 11781,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/8X1BTSaUyF5rc0malaaQovpxC3f.jpg",
    id: 1418,
    name: "The Big Bang Theory",
    original_language: "en",
    original_name: "The Big Bang Theory",
    overview:
      "The sitcom is centered on five characters living in Pasadena, California: roommates Leonard Hofstadter and Sheldon Cooper; Penny, a waitress and aspiring actress who lives across the hall; and Leonard and Sheldon's equally geeky and socially awkward friends and co-workers, mechanical engineer Howard Wolowitz and astrophysicist Raj Koothrappali. The geekiness and intellect of the four guys is contrasted for comic effect with Penny's social skills and common sense.",
    poster_path: "/ooBGRQBdbGzBxAVfExiO8r7kloA.jpg",
    media_type: "tv",
    genre_ids: [35],
    popularity: 101.069,
    first_air_date: "2007-09-24",
    vote_average: 7.879,
    vote_count: 10023,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/hpU2cHC9tk90hswCFEpf5AtbqoL.jpg",
    id: 456,
    name: "The Simpsons",
    original_language: "en",
    original_name: "The Simpsons",
    overview:
      "Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.",
    poster_path: "/zI3E2a3WYma5w8emI35mgq5Iurx.jpg",
    media_type: "tv",
    genre_ids: [10751, 16, 35],
    popularity: 346.398,
    first_air_date: "1989-12-17",
    vote_average: 7.994,
    vote_count: 8883,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/6LWy0jvMpmjoS9fojNgHIKoWL05.jpg",
    id: 1399,
    name: "Game of Thrones",
    original_language: "en",
    original_name: "Game of Thrones",
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    media_type: "tv",
    genre_ids: [10765, 18, 10759],
    popularity: 331.202,
    first_air_date: "2011-04-17",
    vote_average: 8.4,
    vote_count: 21227,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/r7zUXadc1saFFSWz8lbUx7q9bkG.jpg",
    id: 1402,
    name: "The Walking Dead",
    original_language: "en",
    original_name: "The Walking Dead",
    overview:
      "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
    poster_path: "/xf9wuDcqlUPWABZNeDKPbZUjWx0.jpg",
    media_type: "tv",
    genre_ids: [10759, 18, 10765],
    popularity: 270.793,
    first_air_date: "2010-10-31",
    vote_average: 8.117,
    vote_count: 15007,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    id: 66732,
    name: "Stranger Things",
    original_language: "en",
    original_name: "Stranger Things",
    overview:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    media_type: "tv",
    genre_ids: [18, 10765, 9648],
    popularity: 202.388,
    first_air_date: "2016-07-15",
    vote_average: 8.631,
    vote_count: 15627,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/l0qVZIpXtIo7km9u5Yqh0nKPOr5.jpg",
    id: 1668,
    name: "Friends",
    original_language: "en",
    original_name: "Friends",
    overview:
      "Six young people from New York City, on their own and struggling to survive in the real world, find the companionship, comfort and support they get from each other to be the perfect antidote to the pressures of life.",
    poster_path: "/bRJOwllemPbE4JTQ0TtcVu9efff.jpg",
    media_type: "tv",
    genre_ids: [35, 18],
    popularity: 168.086,
    first_air_date: "1994-09-22",
    vote_average: 8.449,
    vote_count: 6921,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/9ijMGlJKqcslswWUzTEwScm82Gs.jpg",
    id: 82856,
    name: "The Mandalorian",
    original_language: "en",
    original_name: "The Mandalorian",
    overview:
      "After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches, earning his keep as a bounty hunter.",
    poster_path: "/eU1i6eHXlzMOlEq0ku1Rzq7Y4wA.jpg",
    media_type: "tv",
    genre_ids: [10765, 10759, 18],
    popularity: 216.855,
    first_air_date: "2019-11-12",
    vote_average: 8.47,
    vote_count: 9094,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/jgb9xICHFX8wTGQ75js4uNbttQs.jpg",
    id: 62688,
    name: "Supergirl",
    original_language: "en",
    original_name: "Supergirl",
    overview:
      "Twenty-four-year-old Kara Zor-El, who was taken in by the Danvers family when she was 13 after being sent away from Krypton, must learn to embrace her powers after previously hiding them. The Danvers teach her to be careful with her powers, until she has to reveal them during an unexpected disaster, setting her on her journey of heroism.",
    poster_path: "/zsaiq8ZclPuneuN7loLEbsh1ANJ.jpg",
    media_type: "tv",
    genre_ids: [18, 10765, 10759],
    popularity: 110.757,
    first_air_date: "2015-10-26",
    vote_average: 7.334,
    vote_count: 3902,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/zymbuoBoL1i94xAOzVJF6IuWLfD.jpg",
    id: 77169,
    name: "Cobra Kai",
    original_language: "en",
    original_name: "Cobra Kai",
    overview:
      "This Karate Kid sequel series picks up 30 years after the events of the 1984 All Valley Karate Tournament and finds Johnny Lawrence on the hunt for redemption by reopening the infamous Cobra Kai karate dojo. This reignites his old rivalry with the successful Daniel LaRusso, who has been working to maintain the balance in his life without mentor Mr. Miyagi.",
    poster_path: "/m7tG5E1EbywuwTsl6hq990So0Bx.jpg",
    media_type: "tv",
    genre_ids: [10759, 18, 35],
    popularity: 110.363,
    first_air_date: "2018-05-02",
    vote_average: 8.211,
    vote_count: 5607,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/gNPWlhUXhyWiHv9qxr57tvT0WwS.jpg",
    id: 60735,
    name: "The Flash",
    original_language: "en",
    original_name: "The Flash",
    overview:
      'After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only "meta-human" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won\'t be long before the world learns what Barry Allen has become...The Flash.',
    poster_path: "/rg8N7x27Ef6PvlIiioLStf9ZaIO.jpg",
    media_type: "tv",
    genre_ids: [18, 10765],
    popularity: 1341.817,
    first_air_date: "2014-10-07",
    vote_average: 7.795,
    vote_count: 10453,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/vNnLAKmoczRlNarxyGrrw0KSOeX.jpg",
    id: 1412,
    name: "Arrow",
    original_language: "en",
    original_name: "Arrow",
    overview:
      "Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea. He returns five years later a changed man, determined to clean up the city as a hooded vigilante armed with a bow.",
    poster_path: "/gKG5QGz5Ngf8fgWpBsWtlg5L2SF.jpg",
    media_type: "tv",
    genre_ids: [80, 18, 9648, 10759],
    popularity: 179.431,
    first_air_date: "2012-10-10",
    vote_average: 6.775,
    vote_count: 5455,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/p7PLOCD4bqLV4sJmeLrwvkufHt3.jpg",
    id: 84958,
    name: "Loki",
    original_language: "en",
    original_name: "Loki",
    overview:
      "After stealing the Tesseract during the events of “Avengers: Endgame,” an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and monitors the timeline. They give Loki a choice: face being erased from existence due to being a “time variant” or help fix the timeline and stop a greater threat.",
    poster_path: "/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg",
    media_type: "tv",
    genre_ids: [18, 10765],
    popularity: 83.986,
    first_air_date: "2021-06-09",
    vote_average: 8.163,
    vote_count: 9902,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/r1tMESor8QuPVKP2VxcVEX6t6ad.jpg",
    id: 43348,
    name: "Pablo Escobar: The Drug Lord",
    original_language: "es",
    original_name: "Pablo Escobar: El Patrón del Mal",
    overview:
      "Pablo is a man with a natural ability for business. Early in his life, Pablo is introduced to the business of cocaine and the power it yields. A young life of crime lands Pablo in and out of jail as he builds is criminal empire. Pablo expands his power through politics but it is not long before his conflicts as a Congressman and a drug lord collide. Pablo has his enemies executed, but not before the United States activates its own war on the Medellin cartel.",
    poster_path: "/jZqm7HFuxfH9P0LFjQZ8nzrCUHP.jpg",
    media_type: "tv",
    genre_ids: [80, 18],
    popularity: 324.673,
    first_air_date: "2012-05-28",
    vote_average: 7.589,
    vote_count: 3248,
    origin_country: ["CO"],
  },
  {
    adult: false,
    backdrop_path: "/nWfpVLgioDXQsAbfL6UJxYz6d3d.jpg",
    id: 16997,
    name: "The Pacific",
    original_language: "en",
    original_name: "The Pacific",
    overview:
      "Track the intertwined real-life stories of three U.S. Marines – Robert Leckie, John Basilone, and Eugene Sledge – across the vast canvas of the Pacific Theater during World War II. A companion piece to the 2001 miniseries Band of Brothers.",
    poster_path: "/x9Y1IMFdY8Ma222KcQadFEau0EB.jpg",
    media_type: "tv",
    genre_ids: [18, 10759, 10768],
    popularity: 39.345,
    first_air_date: "2010-03-14",
    vote_average: 7.733,
    vote_count: 2075,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/34OGjFEbHj0E3lE2w0iTUVq0CBz.jpg",
    id: 87739,
    name: "The Queen's Gambit",
    original_language: "en",
    original_name: "The Queen's Gambit",
    overview:
      "In a Kentucky orphanage in the 1950s, a young girl discovers an astonishing talent for chess while struggling with addiction.",
    poster_path: "/zU0htwkhNvBQdVSIKB9s6hgVeFK.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 51.312,
    first_air_date: "2020-10-23",
    vote_average: 8.539,
    vote_count: 3582,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/5vUux2vNUTqwCzb7tVcH18XnsF.jpg",
    id: 113988,
    name: "Dahmer – Monster: The Jeffrey Dahmer Story",
    original_language: "en",
    original_name: "Dahmer – Monster: The Jeffrey Dahmer Story",
    overview:
      "This series examines the gruesome and horrific true crimes of Jeffrey Dahmer and the systemic failures that enabled one of America’s most notorious serial killers to continue his murderous spree in plain sight for over a decade.",
    poster_path: "/f2PVrphK0u81ES256lw3oAZuF3x.jpg",
    media_type: "tv",
    genre_ids: [80, 18],
    popularity: 66.397,
    first_air_date: "2022-09-21",
    vote_average: 8.086,
    vote_count: 2107,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/rkB4LyZHo1NHXFEDHl9vSD9r1lI.jpg",
    id: 94605,
    name: "Arcane",
    original_language: "en",
    original_name: "Arcane",
    overview:
      "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.",
    poster_path: "/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
    media_type: "tv",
    genre_ids: [16, 10765, 10759, 18],
    popularity: 58.06,
    first_air_date: "2021-11-06",
    vote_average: 8.755,
    vote_count: 3091,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/mRwV4W2BAEpte7xlawJP4fsBpmS.jpg",
    id: 13916,
    name: "Death Note",
    original_language: "ja",
    original_name: "DEATH NOTE",
    overview:
      "Light Yagami is an ace student with great prospects—and he’s bored out of his mind. But all that changes when he finds the Death Note, a notebook dropped by a rogue Shinigami death god. Any human whose name is written in the notebook dies, and Light has vowed to use the power of the Death Note to rid the world of evil. But will Light succeed in his noble goal, or will the Death Note turn him into the very thing he fights against?",
    poster_path: "/iigTJJskR1PcjjXqxdyJwVB3BoU.jpg",
    media_type: "tv",
    genre_ids: [16, 9648, 10765],
    popularity: 68.367,
    first_air_date: "2006-10-04",
    vote_average: 8.642,
    vote_count: 3430,
    origin_country: ["JP"],
  },
];
